### PR TITLE
Add support for mounting any path as needed

### PR DESCRIPTION
**Pull request by halkeye**
I use https://github.com/juliohm1978/kubernetes-cifs-volumedriver/ for mounting directories from my nas. I also want to mount some local devices so i can do hardware encoding.

### CODE REVIEW

**Comment by brianmcarey** [comment]
Yeah makes sense to me. I use the intel gpu plugin for hardware encoding - works pretty well!

**Comment by halkeye** [comment]
ooooh, which device is that?

**Comment by halkeye** [comment]
Oh looks like you don't need a device id for that. Thanks

**Comment by brianmcarey** [comment]
https://github.com/intel/intel-device-plugins-for-kubernetes#gpu-device-plugin

**Comment by halkeye** [comment]
Awesome~ thanks, I'll do that!

**Pull request merged**
